name: list_image
description: Memory Leak Images

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  image: any
