name: foo_devtools_extension
description: A Flutter web app for the package:foo DevTools extension.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.1.0-94.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  devtools_extensions:
    path: ../../

dependency_overrides:
  devtools_app_shared:
    path: ../../../devtools_app_shared
  devtools_extensions:
    path: ../../
  devtools_shared:
    path: ../../../devtools_shared
