// Copyright 2024 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file or at https://developers.google.com/open-source/licenses/bsd.

enum HttpRequestDataKeys {
  connectionInfo,
  contentLength,
  request,
  method,
  cookies,
  headers,
  text,
  followRedirects,
  maxRedirects,
  persistentConnection,
  proxyDetails,
  error,
  response,
  statusCode,
  redirects,
  isolateId,
  uri,
  id,
  startTime,
  events,
  timestamp,
  event,
  compressionState,
  isRedirect,
  reasonPhrase,
  requestBody,
  responseBody,
  endTime,
  arguments,
  host,
  username,
  isDirect,
}
