// Mocks generated by Mockito 5.1.0 from annotations
// in devtools_app/test/typed_data_variable_test.dart.
// Do not manually edit this file.

// @dart=2.9

import 'package:devtools_app/src/service/vm_service_wrapper.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [VmServiceWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockVmServiceWrapper extends _i1.Mock implements _i2.VmServiceWrapper {
  MockVmServiceWrapper() {
    _i1.throwOnMissingStub(this);
  }
}
