name: leak_tracking
description: See https://github.com/flutter/devtools/issues/3951.

version: 0.0.1

repository: https://github.com/flutter/devtools/tree/master/packages/memory_tools

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  intl: ^0.17.0

dev_dependencies:
  test: ^1.21.2
  build_runner: ^2.0.4
  mockito: ^5.1.0
