include: package:lints/recommended.yaml

analyzer:
  exclude:
    - flutter-sdk/

linter:
  rules:
    # - avoid_dynamic_calls
    - depend_on_referenced_packages
    - directives_ordering
    - sort_pub_dependencies
