# Copyright 2025 The Flutter Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file or at https://developers.google.com/open-source/licenses/bsd.
name: devtools_tool
description: A repo management tool for DevTools.
publish_to: none

environment:
  sdk: ">=3.7.0-160.0.dev <4.0.0"

resolution: workspace

executables:
  dt: dt

dependencies:
  args: ^2.4.2
  cli_util: ^0.4.1
  collection: ^1.19.0
  io: ^1.0.4
  meta: ^1.18.0
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  # TODO(https://github.com/flutter/devtools/issues/9771): Update to published version
  dart_skills_lint:
    git:
      url: https://github.com/flutter/skills
      path: tool/dart_skills_lint
      ref: e4497873950727ee781fa411c1a2f624b1ec50c6
  logging: ^1.1.1
  test: ^1.25.8
