name: memory_leak
description: Flutter memory leak example app to serve as a DevTools case study.

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
