theme: jekyll-theme-primer
# This should match the path where the live deployment is, so `jekyll serve`
# puts the local version at the same relative path.
baseurl: /devtools
title: DevTools (preview)
# Set the repository so that site.github.xxx works when serving locally.
repository: flutter/devtools
kramdown:
  parse_block_html: true
plugins:
  - jekyll-redirect-from
