import 'package:devtools_app/html_main.dart' as devtools;

/// Launches the pure-html DevTools web app.
///
/// When the app is built with the flutter tool, this main.dart file
/// will be overridden by a main.dart file generated by the flutter tool.
void main() {
  devtools.main();
}
