include: ../analysis_options.yaml

analyzer:
  exclude:
    - build/**
    - lib/generated_plugin_registrant.dart
    - macos/
    # Syntax highlighting test files may include or lint-violating code
    # for testing so should be ignored. Uncomment this while modifying
    # these files if you want to ensure code is not invalid except where
    # expected.
    - test/test_infra/test_data/syntax_highlighting/**

dart_code_metrics:
  metrics-exclude:
    - test/**
    - test/test_infra/test_data/**
