include: ../../analysis_options.yaml

analyzer:
  exclude:
    - lib/generated_plugin_registrant.dart
    - macos/
# Enable this option if you need to test whether the inspector_polyfill_script is compatible with
# versions of flutter that require null safety.
#  enable-experiment:
#    - non-nullable
