targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        options:
          dart2js_args:
          - -O1
      # We don't generate any mocks in this package.
      mockito|mockBuilder:
        enabled: false
      stager|stagerAppBuilder:
        generate_for:
          - test/test_infra/scenes/**.dart
